### ISSUE TITLE
Even after implementing this implementation 'com.github.TalbotGooday:AndroidPdfViewer:Tag' App get crashed.

### ISSUE THREAD

**Issue by jazzbpn** [TalbotGooday/AndroidPdfViewer#3]
1. App get crashed using this dependency:
      ` /** PDF Dependencies */
        //  implementation 'com.github.barteksc:android-pdf-viewer:3.2.0-beta.1'
        implementation 'com.github.TalbotGooday:AndroidPdfViewer:3.1.0-beta.3'`

2. And Sample code Issue:
Once scroll to bottom unable to swipe top due to this **pageFling(..)** property. Commenting **pageFling(..)** resolve this swipe to top issue.

**Comment by TalbotGooday** [comment]
Hi. Can you send me the stacktrace, please. I would be very grateful if you could share an example of the code that causes the crashes and / or other problems.

**Comment by jazzbpn** [comment]
I tried the sample from the GitHub. It works! Thank you for the update.
